version: "3.3"

services:
  postgres:
    container_name: postgres
    image: library/postgres
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - local-keycloak
  
  redis-master:
    container_name: redis
    networks:
      - local-keycloak
    image: redis:5.0.4-alpine
    restart: always
    ports:
      - 127.0.0.1:6379:6379

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin_password
    ports:
      - "8484:8080"
    depends_on:
      - postgres
    links:
      - "postgres:postgres"
    restart: unless-stopped
    networks:
      - local-keycloak

networks:
  local-keycloak:
